# Generated by Django 5.1.4 on 2024-12-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='encrypted_content',
            new_name='content',
        ),
    ]
